#!/bin/bash
# Download Android Studio
wget -q --show-progress "https://github.com/FershoUno/packages/releases/download/v1.0.0/android-studio_2023.2.1_amd64.deb"
apt update
apt install ./android-studio_2023.2.1_amd64.deb -y

# remove pseint
rm -f android-studio_2023.2.1_amd64.deb
