#!/bin/bash

apt update
# Download and Install 
wget -q --show-progress  "https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb" -O packages-microsoft-prod.deb
apt install ./packages-microsoft-prod.deb
rm -f packages-microsoft-prod.deb

# Installation SDK-8.0 y ASP.NET Core from repository
apt update
apt install dotnet-sdk-8.0 aspnetcore-runtime-8.0 -y

