#!/bin/bash
# Download Pseint
wget -q --show-progress "https://github.com/FershoUno/packages/releases/download/v1.0.0/pseint-minunux_20240122_amd64.deb"
apt update
apt install ./pseint-minunux_20240122_amd64.deb -y

# remove pseint
rm -f pseint-minunux_20240122_amd64.deb
