#!/bin/bash

apt update
wget -q --show-progress "https://github.com/rustdesk/rustdesk/releases/download/1.2.3-1/rustdesk-1.2.3-1-x86_64.deb"
apt install ./rustdesk-1.2.3-1-x86_64.deb -y
rm -f rustdesk-1.2.3-1-x86_64.deb

