#!/bin/bash

dpkg --add-architecture i386 && sudo apt update
wget -O /etc/apt/trusted.gpg.d/vitexsoftware.gpg http://repo.vitexsoftware.cz/keyring.gpg
echo "deb http://repo.vitexsoftware.cz $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/vitexsoftware.list
apt update
apt install wine wine32:i386 -y
apt install winbox -y
